In [1]:
import numpy as np
import typing as tp

In [2]:
def find_max_sum_segment(array: tp.List[int], k: int) -> int:
    arr = np.array(array)
    size = arr.size
    arr = arr[np.newaxis, :]

    arr = np.repeat(arr, size, axis=0)

    arr = np.triu(arr)
    arr = (np.tril(arr, k=k-1))[0:(size - k + 1)]

    ones = np.ones((1, size)).T

    return np.sort(arr @ ones, axis=0)[size - k, 0].astype('int32')

In [3]:
arr = np.array([-5, 3, -6, 1])
k = 4

find_max_sum_segment(arr, 4)

-7

In [4]:
size = arr.size
arr = arr[np.newaxis, :]

arr = np.repeat(arr, size, axis=0)
arr

array([[-5,  3, -6,  1],
       [-5,  3, -6,  1],
       [-5,  3, -6,  1],
       [-5,  3, -6,  1]])

In [5]:
arr = np.triu(arr)
arr

array([[-5,  3, -6,  1],
       [ 0,  3, -6,  1],
       [ 0,  0, -6,  1],
       [ 0,  0,  0,  1]])

In [6]:
arr = (np.tril(arr, k=k))[0:(size - k + 1)]
arr

array([[-5,  3, -6,  1]])

In [7]:
ones = np.ones((1, size)).T
arr @ ones

array([[-7.]])

In [8]:
import torch

In [9]:
a = torch.tensor([1, 2, .17])

In [11]:
for i in range(10):
    a += 1

In [12]:
a

tensor([11.0000, 12.0000, 10.1700])