In [28]:
import numpy as np
import typing as tp

import pandas as pd

In [29]:
def matrix_multiplication(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    return (a[:, :, np.newaxis] * (b[np.newaxis, :])).sum(axis=1)

In [ ]:
sql = pd.read_sql()

In [31]:
first = np.array([[4, 5],
                  [3, 6],
                  [2, 7],
                  [1, 6]])

second = np.array([[2, 1, 7],
                  [3, 4, 8]])

first = first[:, :, np.newaxis]
second = second[np.newaxis, :]

first

array([[[4],
        [5]],

       [[3],
        [6]],

       [[2],
        [7]],

       [[1],
        [6]]])

In [34]:
second

array([[[2, 1, 7],
        [3, 4, 8]]])

In [33]:
first * second

array([[[ 8,  4, 28],
        [15, 20, 40]],

       [[ 6,  3, 21],
        [18, 24, 48]],

       [[ 4,  2, 14],
        [21, 28, 56]],

       [[ 2,  1,  7],
        [18, 24, 48]]])